@startuml DiagrammePaquetage
!pragma layout smetana

hide stereotype

skinparam component {
  BorderColor black
  BackgroundColor #SkyBlue
  FontStyle bold
}

package "Export de données de santé" #Seashell   {
        package "Portabilité de données LGC" #Azure {
          component "Export d'archive de portabilité" [[specifications.html{Voir les spécifications}]]
        }
        package "Echanges de documents de Santé via MSS" #Azure {
          component "Export d'archive XDM via MSS" [[https://esante.gouv.fr/volet-echange-de-documents-de-sante{Voir les spécifications}]]
        }
}

@enduml