@startuml sf-concepts-portabilite
!theme carbon-gray
skinparam classAttributeIconSize 0
skinparam classAttributeFontSize 10
skinparam padding 2
skinparam noteFontSize 11
left to right direction
skinparam ranksep 50
skinparam nodesep 50
skinparam linetype ortho

''Archives ZIP''

''Répertoire




''Fichiers''
rectangle "**Archive de portabilité**\n[[StructureDefinition-pdlgc-archive-portabilite Archive de portabilité]]" as export #Pink
rectangle "**Signature**\n[[StructureDefinition-pdlgc-signature SIGN.XML]]" as signature #Lavender
rectangle "**Manifest de Portabilité**\n[[StructureDefinition-pdlgc-manifest MANIFEST.XML]]" as manifest #Lavender
rectangle "**Documentation d'export**" as doc #PeachPuff
rectangle "**Readme**\n[[StructureDefinition-pdlgc-readme README.TXT]]" as readme #Lavender

rectangle "**Archive de données transverses**\n[[StructureDefinition-pdlgc-archive-transverse Archive de données transverses]]" as transverse #Pink
rectangle "**Document Transverse périmètre pivot**\n[[sf-perimetre-pivot.html Périmètre pivot]]" as Tpivot #Lavender
rectangle "**Document Transverse hors périmètre pivot**" as Thorspivot #Lavender

rectangle "**Archive XDM patient**\n(données médicales)\n[[StructureDefinition-pdlgc-archive-patient Archive XDM patient]]" as archivepat #Pink
rectangle "**PDF pour consultation**" as PDF #PeachPuff
rectangle "**Index**\n[[StructureDefinition-pdlgc-index INDEX.HTM]]" as index #Lavender
rectangle "**Lot de soumission**" as lot #PeachPuff
rectangle "**Metadata**\n[[StructureDefinition-pdlgc-metadata METADATA.XML]]" as metadata #Lavender
rectangle "**Document Patient périmètre pivot**\n[[sf-perimetre-pivot.html Périmètre pivot]]" as Ppivot #Lavender
rectangle "**Document Patient hors périmètre pivot**" as Phorspivot #Lavender



''Liens''
export -- "1..1" manifest
export -- "1..1" readme
export -- "1..1" signature
export -- "1..*" archivepat
export -- "0..1" transverse
export -- "1..1" doc
archivepat -- "1..1" readme
archivepat -- "1..1" index
archivepat -- "1..1" lot
archivepat -- "1..*" PDF
lot -- "1..1" metadata
lot -- "1..*" Ppivot
lot -- "0..*" Phorspivot
transverse -- "1..*" Tpivot
transverse -- "0..*" Thorspivot
transverse -- "1..1" readme


''Légende''
legend left
|= Légende|= Type|
|<#Pink>| Archive Zip |
|<#PeachPuff>| Répertoire |
|<#Lavender>| fichiers |
endlegend

@enduml
