// ===========================================================================
// Archive de Portabilité - Signature XAdES (SIGN.XML)
// ===========================================================================


Logical: PDLGCSignature
Id: pdlgc-signature
Title: "PDLGC Signature"
Description: "signature XAdES de l'archive attestant de l'imputabilité et l'intégrité des données"


// ── Structure générale ──────────────────────────────────────────────────────

* SignedInfo 1..1 BackboneElement "Informations couvertes par la signature"
  * CanonicalizationMethod 1..1 uri "Algorithme de canonicalisation XML. Valeur recommandée : http://www.w3.org/2001/10/xml-exc-c14n#."
  * SignatureMethod 1..1 uri "Algorithme cryptographique utilisé pour signer. Valeur recommandée : http://www.w3.org/2001/04/xmldsig-more#rsa-sha256."
  * References 2..2 BackboneElement "Références couvertes par la signature. La première référence pointe vers le Manifest (#Manifest). La seconde référence pointe vers les SignedProperties XAdES (#signedProperties)."
    * URI 1..1 uri "URI de l'objet signé. (#manifest ou #signedProperties)"
    * Type 0..1 string "Type de la référence"
    * DigestMethod 1..1 string "Algorithme de hachage de la référence. Valeur recommandée : http://www.w3.org/2001/04/xmlenc#sha256"
    * DigestValue 1..1 base64Binary "Empreinte base64 de l'objet référencé"

* signatureValue 1..1 base64Binary "Valeur de la signature cryptographique. Base64 de la signature calculée sur les références déclarées dans SignedInfo."

// ── Informations sur le signataire ─────────────────────────────────────────

* keyInfo 1..1 BackboneElement "Informations sur la clé de signature"
  * x509Data 1..1 BackboneElement "Données du certificat X.509 du signataire"
    * x509Certificate 1..1 base64Binary "Certificat X.509 du signataire (base64 DER). Certificat délivré par une autorité de certification reconnue par le référentiel RGS."
    * x509IssuerSerial 0..1 BackboneElement "Émetteur et numéro de série du certificat"
      * x509IssuerName 1..1 string "Nom distinctif de l'autorité de certification"
      * x509SerialNumber 1..1 string "Numéro de série du certificat"

// ── Périmètre de la signature ───────────────────────────────────────────────

* Object 1..* BackboneElement "Périmètre des objets couverts par la signature"
  * Manifest 0..1 BackboneElement "Périmètre des objets couverts par la signature. Id fixé à manifest"
    * Id 1..1 string "Valeur fixée à 'manifest'."
    * Reference 1..* BackboneElement "Références aux objets signés. Chaque référence pointe vers un fichier constitutif du périmètre signé de l'archive de portabilité (MANIFEST.XML, archives XDM patient et archive transverse)."
      * Uri 1..1 string "URI de la référence"
      * DigestMethod 1..1 string "Algorithme de hachage de la référence. Valeur recommandée : http://www.w3.org/2001/04/xmlenc#sha256"
      * DigestValue 1..1 base64Binary "Empreinte base64 de l'objet référencé"
  * QualifyingProperties 0..1 BackboneElement "Propriétés qualifiantes XAdES"
    // ── Propriétés signées (XAdES SignedProperties) ─────────────────────────────  
    * Target 1..1 string "Signature concernée"
    * SignedProperties 1..1 BackboneElement "Propriétés incluses dans la signature"
      * Id 1..1 string "Valeur fixée à 'signedProperties'."
      * SignedSignatureProperties 1..1 BackboneElement "Propriétés de la signature"
        * SigningTime 0..1 dateTime "Date et heure de signature déclarée par le signataire (ISO 8601)"
          """Distincte de l'horodatage qualifié porté par les UnsignedProperties
          (XAdES-T et supérieur). Pour XAdES-B, seul signingTime est présent."""
        * SigningCertificateV2 1..1 BackboneElement "Référence au certificat de signature"
          """Lie cryptographiquement la signature au certificat du signataire."""
          * CertDigest 1..1 BackboneElement "Empreinte du certificat"
            * DigestMethod 1..1 string "Algorithme de hachage (SHA-256 recommandé)"
            * DigestValue 1..1 string "Empreinte base64 du certificat X.509"
          * IssuerSerial 0..1 BackboneElement "Informations d'identification du certificat."
            * X509IssuerName 1..1 string "Nom de l'autorité de certification."
            * X509SerialNumber 1..1 string "Numéro de série du certificat."
          * SignaturePolicyIdentifier 0..1 BackboneElement "Politique de signature appliquée."
            * SignaturePolicyId 0..1 BackboneElement "Politique de signature explicitement identifiée."
              * SigPolicyId 1..1 string "Identifiant de la politique."
              * SigPolicyHash 1..1 BackboneElement "Empreinte de la politique."
                * DigestMethod 1..1 uri "Algorithme de calcul de l'empreinte."
                * DigestValue 1..1 base64Binary "Empreinte de la politique."
            * SignaturePolicyImplied 0..1 boolean "Indique que la politique de signature est implicite."
          * SignatureProductionPlace 0..1 BackboneElement "Lieu déclaré de création de la signature."
            * City 0..1 string "Ville."
            * StateOrProvince 0..1 string "État ou région."
            * PostalCode 0..1 string "Code postal."
            * CountryName 0..1 string "Pays."
          * SignerRole 0..1 BackboneElement "Rôle déclaré du signataire."
            * ClaimedRoles 0..1 BackboneElement "Rôles déclarés par le signataire."
              * ClaimedRole 1..* string "Libellé du rôle déclaré."
            * CertifiedRoles 0..1 BackboneElement "Rôles certifiés."
              * CertifiedRole 1..* string "Rôle certifié."
      * SignedDataObjectProperties 0..1 BackboneElement "Propriétés des objets signés"
        * DataObjectFormat 0..* BackboneElement "Format des objets signés référencés"
          * ObjectReference 1..1 string "Référence à l'élément Reference concerné"
          * MimeType 1..1 string "Type MIME de l'objet signé"
          * Description 0..1 string "Description de l'objet signé"
          * ObjectIdentifier 0..1 BackboneElement "Identifiant normalisé du type d'objet."
            * Identifier 1..1 uri "Identifiant unique."
            * Description 0..1 string "Description de l'identifiant."
          * Encoding 0..1 uri "Encodage utilisé pour l'objet."
        * CommitmentTypeIndication 0..* BackboneElement "Engagement pris par le signataire vis-à-vis de l'objet signé."
          * CommitmentTypeId 1..1 uri "Identifiant du type d'engagement."
          * ObjectReference 0..* string "Références des objets concernés."
          * AllSignedDataObjects 0..1 boolean "Indique que l'engagement s'applique à tous les objets signés."
          * CommitmentTypeQualifiers 0..1 BackboneElement "Informations complémentaires relatives à l'engagement."
        * AllDataObjectsTimeStamp 0..* BackboneElement "Horodatage portant sur l'ensemble des objets signés."
          * CanonicalizationMethod 0..1 uri "Algorithme de canonicalisation."
          * EncapsulatedTimeStamp 1..* base64Binary "Jeton d'horodatage RFC 3161."
        * IndividualDataObjectsTimeStamp 0..* BackboneElement "Horodatage portant sur un ou plusieurs objets signés."
          * ObjectReference 1..* string "Références des objets concernés."
          * CanonicalizationMethod 0..1 uri "Algorithme de canonicalisation."
          * EncapsulatedTimeStamp 1..* base64Binary "Jeton d'horodatage RFC 3161."
      // ── Propriétés non signées (XAdES-T et supérieur uniquement) ────────────────
      * UnsignedProperties 0..1 BackboneElement "Propriétés non incluses dans la signature (XAdES-T et LT)"
        * Id 1..1 string "Valeur fixée à 'unsignedProperties'."
        * UnsignedSignatureProperties 0..1 BackboneElement "Propriétés non incluses dans la signature"
          * CounterSignature 0..* BackboneElement "Contre-signatures appliquées à la signature."
            * Signature 1..1 BackboneElement "Signature de contre-signature."
          * SignatureTimeStamp 0..* BackboneElement "Jeton d'horodatage qualifié (XAdES-T minimum). Horodatage de la valeur de signature par une Autorité d'Horodatage
              qualifiée eIDAS. Garantit la date de signature de manière opposable, indépendamment de la déclaration signingTime du signataire."
            * CanonicalizationMethod 1..1 string "Algorithme de canonicalisation appliqué avant horodatage"
            * EncapsulatedTimeStamp 1..1 string "Jeton d'horodatage encodé en base64 (format RFC 3161)"
          * CompleteCertificateRefs 0..1 BackboneElement "Références vers les certificats nécessaires à la validation."
            * CertRefs 1..* BackboneElement "Référence vers un certificat."
              * CertDigest 1..1 BackboneElement "Empreinte du certificat"
                * DigestMethod 1..1 string "Algorithme de hachage (SHA-256 recommandé)"
                * DigestValue 1..1 string "Empreinte base64 du certificat X.509"
          * CompleteRevocationRefs 0..1 BackboneElement "Références vers les informations de révocation."
            * OCSPRefs 0..1 BackboneElement "Références vers des réponses OCSP."
            * CRLRefs 0..1 BackboneElement "Références vers des listes de révocation."
          * AttributeCertificateRefs 0..1 BackboneElement "Références vers des certificats d'attribut."
          * AttributeRevocationRefs 0..1 BackboneElement "Références vers les informations de révocation des certificats d'attribut."
          * SigAndRefsTimeStamp 0..* BackboneElement "Horodatage couvrant la signature et les références de validation."
            * EncapsulatedTimeStamp 1..* string "Jeton d'horodatage encodé en base64 (format RFC 3161)"
          * RefsOnlyTimeStamp 0..* BackboneElement "Horodatage couvrant uniquement les références de validation."
            * EncapsulatedTimeStamp 1..* string "Jeton d'horodatage encodé en base64 (format RFC 3161)"
          * CertificateValues 0..1 BackboneElement "Valeurs des certificats de la chaîne (XAdES-LT). Certificats de la chaîne de confiance embarqués dans la signature pour permettre la validation hors ligne après expiration."
            * EncapsulatedX509Certificate 1..* string "Certificat X.509 de la chaîne (base64 DER)"
          * RevocationValues 0..1 BackboneElement "Données de révocation (XAdES-LT). Réponses OCSP ou listes CRL embarquées dans la signature."
            * OcspValues 0..* string "Réponses OCSP encodées en base64"
            * CrlValues 0..* string "Listes CRL encodées en base64"
          * ArchiveTimeStamp 0..* BackboneElement "Horodatage garantissant la validité de la signature sur le long terme."
            * EncapsulatedTimeStamp 1..* base64Binary "Jeton d'horodatage."
        * UnsignedDataObjectProperties 0..1 BackboneElement "Propriétés non signées relatives aux objets couverts par la signature."
          * Extension 0..* BackboneElement "Extension spécifique au profil d'implémentation."