// ===========================================================================
// Archive de Portabilité - Signature XAdES (SIGN.XML)
// ===========================================================================


Logical: PDLGCSignature
Id: pdlgcSignature
Title: "PDLGC Signature"
Description: "signature XAdES de l'archive attestant de l'imputabilité et l'intégrité des données"


// ── Structure générale ──────────────────────────────────────────────────────

* signedInfo 1..1 BackboneElement "Informations couvertes par la signature"
  * canonicalizationMethod 1..1 uri "Algorithme de canonicalisation XML. Valeur recommandée : http://www.w3.org/2001/10/xml-exc-c14n#."
  * signatureMethod 1..1 uri "Algorithme cryptographique utilisé pour signer. Valeur recommandée : http://www.w3.org/2001/04/xmldsig-more#rsa-sha256."
  * references 2..2 BackboneElement "Références couvertes par la signature. La première référence pointe vers le Manifest (#Manifest). La seconde référence pointe vers les SignedProperties XAdES (#signedProperties)."
    * uri 1..1 uri "URI de l'objet signé. (#manifest ou #signedProperties)"
    * type 0..1 string "Type de la référence"
    * digestMethod 1..1 string "Algorithme de hachage de la référence. Valeur recommandée : http://www.w3.org/2001/04/xmlenc#sha256"
    * digestValue 1..1 base64Binary "Empreinte base64 de l'objet référencé"

* signatureValue 1..1 base64Binary "Valeur de la signature cryptographique. Base64 de la signature calculée sur les références déclarées dans SignedInfo."

// ── Informations sur le signataire ─────────────────────────────────────────

* keyInfo 1..1 BackboneElement "Informations sur la clé de signature"
  * x509Data 1..1 BackboneElement "Données du certificat X.509 du signataire"
    * x509Certificate 1..1 base64Binary "Certificat X.509 du signataire (base64 DER). Certificat délivré par une autorité de certification reconnue par le référentiel RGS."
    * x509IssuerSerial 0..1 BackboneElement "Émetteur et numéro de série du certificat"
      * x509IssuerName 1..1 string "Nom distinctif de l'autorité de certification"
      * x509SerialNumber 1..1 string "Numéro de série du certificat"

// ── Périmètre de la signature ───────────────────────────────────────────────

* object 1..* BackboneElement "Périmètre des objets couverts par la signature"
  * manifest 0..1 BackboneElement "Périmètre des objets couverts par la signature. Id fixé à manifest"
    * id 1..1 string "Valeur fixée à 'manifest'."
    * reference 1..* BackboneElement "Références aux objets signés. Chaque référence pointe vers un fichier constitutif du périmètre signé de l'archive de portabilité (MANIFEST.XML, archives XDM patient et archive transverse)."
      * uri 1..1 string "URI de la référence"
      * digestMethod 1..1 string "Algorithme de hachage de la référence. Valeur recommandée : http://www.w3.org/2001/04/xmlenc#sha256"
      * digestValue 1..1 base64Binary "Empreinte base64 de l'objet référencé"
  * qualifyingProperties 0..1 BackboneElement "Propriétés qualifiantes XAdES"
    // ── Propriétés signées (XAdES SignedProperties) ─────────────────────────────  
    * target 1..1 string "Signature concernée"
    * signedProperties 1..1 BackboneElement "Propriétés incluses dans la signature"
      * id 1..1 string "Valeur fixée à 'signedProperties'."
      * signedSignatureProperties 1..1 BackboneElement "Propriétés de la signature"
        * signingTime 0..1 dateTime "Date et heure de signature déclarée par le signataire (ISO 8601)"
          """Distincte de l'horodatage qualifié porté par les UnsignedProperties
          (XAdES-T et supérieur). Pour XAdES-B, seul signingTime est présent."""
        * signingCertificateV2 1..1 BackboneElement "Référence au certificat de signature"
          """Lie cryptographiquement la signature au certificat du signataire."""
          * certDigest 1..1 BackboneElement "Empreinte du certificat"
            * digestMethod 1..1 string "Algorithme de hachage (SHA-256 recommandé)"
            * digestValue 1..1 string "Empreinte base64 du certificat X.509"
          * issuerSerial 0..1 BackboneElement "Informations d'identification du certificat."
            * x509IssuerName 1..1 string "Nom de l'autorité de certification."
            * x509SerialNumber 1..1 string "Numéro de série du certificat."
          * signaturePolicyIdentifier 0..1 BackboneElement "Politique de signature appliquée."
            * signaturePolicyId 0..1 BackboneElement "Politique de signature explicitement identifiée."
              * sigPolicyId 1..1 string "Identifiant de la politique."
              * sigPolicyHash 1..1 BackboneElement "Empreinte de la politique."
                * digestMethod 1..1 uri "Algorithme de calcul de l'empreinte."
                * digestValue 1..1 base64Binary "Empreinte de la politique."
            * signaturePolicyImplied 0..1 boolean "Indique que la politique de signature est implicite."
          * signatureProductionPlace 0..1 BackboneElement "Lieu déclaré de création de la signature."
            * city 0..1 string "Ville."
            * stateOrProvince 0..1 string "État ou région."
            * postalCode 0..1 string "Code postal."
            * countryName 0..1 string "Pays."
          * signerRole 0..1 BackboneElement "Rôle déclaré du signataire."
            * claimedRoles 0..1 BackboneElement "Rôles déclarés par le signataire."
              * claimedRole 1..* string "Libellé du rôle déclaré."
            * certifiedRoles 0..1 BackboneElement "Rôles certifiés."
              * certifiedRole 1..* string "Rôle certifié."
      * signedDataObjectProperties 0..1 BackboneElement "Propriétés des objets signés"
        * dataObjectFormat 0..* BackboneElement "Format des objets signés référencés"
          * objectReference 1..1 string "Référence à l'élément Reference concerné"
          * mimeType 1..1 string "Type MIME de l'objet signé"
          * description 0..1 string "Description de l'objet signé"
          * objectIdentifier 0..1 BackboneElement "Identifiant normalisé du type d'objet."
            * identifier 1..1 uri "Identifiant unique."
            * description 0..1 string "Description de l'identifiant."
          * encoding 0..1 uri "Encodage utilisé pour l'objet."
        * commitmentTypeIndication 0..* BackboneElement "Engagement pris par le signataire vis-à-vis de l'objet signé."
          * commitmentTypeId 1..1 uri "Identifiant du type d'engagement."
          * objectReference 0..* string "Références des objets concernés."
          * allSignedDataObjects 0..1 boolean "Indique que l'engagement s'applique à tous les objets signés."
          * commitmentTypeQualifiers 0..1 BackboneElement "Informations complémentaires relatives à l'engagement."
        * allDataObjectsTimeStamp 0..* BackboneElement "Horodatage portant sur l'ensemble des objets signés."
          * canonicalizationMethod 0..1 uri "Algorithme de canonicalisation."
          * encapsulatedTimeStamp 1..* base64Binary "Jeton d'horodatage RFC 3161."
        * individualDataObjectsTimeStamp 0..* BackboneElement "Horodatage portant sur un ou plusieurs objets signés."
          * objectReference 1..* string "Références des objets concernés."
          * canonicalizationMethod 0..1 uri "Algorithme de canonicalisation."
          * encapsulatedTimeStamp 1..* base64Binary "Jeton d'horodatage RFC 3161."
    // ── Propriétés non signées (XAdES-T et supérieur uniquement) ────────────────
    * unsignedProperties 0..1 BackboneElement "Propriétés non incluses dans la signature (XAdES-T et LT)"
      * id 1..1 string "Valeur fixée à 'unsignedProperties'."
      * unsignedSignatureProperties 0..1 BackboneElement "Propriétés non incluses dans la signature"
        * counterSignature 0..* BackboneElement "Contre-signatures appliquées à la signature."
          * signature 1..1 BackboneElement "Signature de contre-signature."
        * signatureTimeStamp 0..* BackboneElement "Jeton d'horodatage qualifié (XAdES-T minimum). Horodatage de la valeur de signature par une Autorité d'Horodatage
            qualifiée eIDAS. Garantit la date de signature de manière opposable, indépendamment de la déclaration signingTime du signataire."
          * canonicalizationMethod 1..1 string "Algorithme de canonicalisation appliqué avant horodatage"
          * encapsulatedTimeStamp 1..1 string "Jeton d'horodatage encodé en base64 (format RFC 3161)"
        * completeCertificateRefs 0..1 BackboneElement "Références vers les certificats nécessaires à la validation."
          * certRefs 1..* BackboneElement "Référence vers un certificat."
            * certDigest 1..1 BackboneElement "Empreinte du certificat"
              * digestMethod 1..1 string "Algorithme de hachage (SHA-256 recommandé)"
              * digestValue 1..1 string "Empreinte base64 du certificat X.509"
        * completeRevocationRefs 0..1 BackboneElement "Références vers les informations de révocation."
          * ocsPRefs 0..1 BackboneElement "Références vers des réponses OCSP."
          * crlRefs 0..1 BackboneElement "Références vers des listes de révocation."
        * attributeCertificateRefs 0..1 BackboneElement "Références vers des certificats d'attribut."
        * attributeRevocationRefs 0..1 BackboneElement "Références vers les informations de révocation des certificats d'attribut."
        * sigAndRefsTimeStamp 0..* BackboneElement "Horodatage couvrant la signature et les références de validation."
          * encapsulatedTimeStamp 1..* string "Jeton d'horodatage encodé en base64 (format RFC 3161)"
        * refsOnlyTimeStamp 0..* BackboneElement "Horodatage couvrant uniquement les références de validation."
          * encapsulatedTimeStamp 1..* string "Jeton d'horodatage encodé en base64 (format RFC 3161)"
        * certificateValues 0..1 BackboneElement "Valeurs des certificats de la chaîne (XAdES-LT). Certificats de la chaîne de confiance embarqués dans la signature pour permettre la validation hors ligne après expiration."
          * encapsulatedX509Certificate 1..* string "Certificat X.509 de la chaîne (base64 DER)"
        * revocationValues 0..1 BackboneElement "Données de révocation (XAdES-LT). Réponses OCSP ou listes CRL embarquées dans la signature."
          * ocspValues 0..* string "Réponses OCSP encodées en base64"
          * crlValues 0..* string "Listes CRL encodées en base64"
        * archiveTimeStamp 0..* BackboneElement "Horodatage garantissant la validité de la signature sur le long terme."
          * encapsulatedTimeStamp 1..* base64Binary "Jeton d'horodatage."
      * unsignedDataObjectProperties 0..1 BackboneElement "Propriétés non signées relatives aux objets couverts par la signature."
        * unsignedDataObjectProperty 0..1 string "Propriétés non signées relatives aux objets couverts par la signature."